### ISSUE TITLE
dns_domain not set via meta-data

### ISSUE THREAD

**Issue by chorrell** [joyent/sdc-vmtools-lx-brand#16]
According to the [vmadm man page](https://github.com/joyent/smartos-live/blob/master/src/vm/man/vmadm.1m.md):

```
dns_domain:

    For OS VMs this specifies the domain value for /etc/hosts that gets set
    at create time. Updating this after create will have no effect.

    type: string (domain name)
    vmtype: OS
    listable: yes
    create: yes
    update: no
    default: local
```

Looking at the zoneinit code, it's not immediately obvious which file is being modified though with the dns_domain value. The man page says /etc/hosts, but you'd think this is something that would be in /etc/resolv.conf?

https://github.com/joyent/zoneinit/blob/master/includes/11-files.sh

It looks like any file in /etc and /opt/local/etc with a `@DOMAINNAME@` value will get the dns_domain value. I can't figure out what files are relevant.

Regardless, we should probably do the expected thing for lx-brand and modify resolv.conf. I will get some clarification on what the expected behaviour is.
